services:
  db:
    image: postgres:15
    env_file: .env

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./rocky:/app
    env_file: .env
    links:
      - db
    depends_on:
      - db